// Copyright 2022 PufStudio. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "TiledLevelAsset.h"
#include "Engine/StaticMeshActor.h"
#include "StaticTiledLevel.generated.h"


UCLASS()
class TILEDLEVELRUNTIME_API AStaticTiledLevel : public AStaticMeshActor
{
	GENERATED_BODY()

public:
	AStaticTiledLevel();

	// Go back to the asset where it came from
	UFUNCTION(CallInEditor, Category="Work flow")
	void RevertToTiledLevel();

	void SetSourceAsset(UTiledLevelAsset* InSourceAsset) { SourceAsset = InSourceAsset; }

private:
	UPROPERTY()
	UTiledLevelAsset* SourceAsset;
	UPROPERTY()
	FVector OriginOffset;
	
	UPROPERTY()
	bool IsAutoGenerated = false;
	

};
